#!/usr/bin/env python3
"""Build references/rest/examples-catalogue.md from a cached Integration Development Guide (maintenance only).

    python scripts/build_examples_catalogue.py --cache <dir written by fetch_beacon_guide.py> --out references/rest/examples-catalogue.md --verified YYYY-MM-DD

For every topic under "REST API Examples" (the Basic Requests, the query-parameter topics and the per-entity
examples) the script extracts the facts a developer needs to find the right request shape, never the page text:
the topic title, the endpoint and entity in the request URL, every distinct request line (method, path and query
string, whitespace-collapsed) and the features the topic says must be enabled. One table row per topic, grouped
by entity, each row linking to the Beacon page. Re-run after every re-fetch; the file is fully regenerated.
"""
import argparse
import glob
import json
import os
import re

BASE = "https://beacon.acumatica.com"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--verified", required=True)
    a = ap.parse_args()

    toc = json.load(open(os.path.join(a.cache, "toc.json"), encoding="utf-8"))
    meta = json.load(open(os.path.join(a.cache, "map.json"), encoding="utf-8"))
    version = next((m["values"][0] for m in meta.get("metadata", []) if m["key"] == "version"), "?")

    groups = {}
    order = []
    for i, t in enumerate(toc, 1):
        pu = t["prettyUrl"]
        if "/REST-API-Examples/" not in pu or t["depth"] != 2:
            continue
        files = glob.glob(os.path.join(a.cache, f"{i:03d}-*.md"))
        if not files:
            continue
        txt = open(files[0], encoding="utf-8").read()
        group = pu.split("/REST-API-Examples/")[1].split("/")[0]
        reqs = re.findall(r"^((?:GET|PUT|POST|PATCH|DELETE) /entity[^\n]*(?:\n[ \t]+[^\n]+)*)", txt, flags=re.M)
        reqs = [" ".join(r.replace(" HTTP/1.1", "").split()) for r in reqs]
        seen = []
        for r in reqs:
            if r not in seen:
                seen.append(r)
        feats = re.findall(r"make sure that (?:the )?([^.]*?) features? (?:are|is) enabled", txt, flags=re.S)
        feats = [" ".join(f.split()) for f in feats]
        feats = [f.split("form, make sure that the ")[-1] for f in feats]  # drop a preceding sentence when the regex spans one
        endpoints = sorted({m.group(1) for r in seen for m in [re.search(r"/entity/([A-Za-z0-9_.]+)/", r)] if m})
        if group not in groups:
            groups[group] = []
            order.append(group)
        groups[group].append({"title": t["title"], "url": BASE + pu, "requests": seen, "features": feats, "endpoints": endpoints})

    n = sum(len(v) for v in groups.values())
    lines = [
        f"<!-- source: Acumatica Integration Development Guide, REST API Examples ({BASE}/r/Integration-Development-Guide/REST-API-Examples) | version: Acumatica ERP {version} (guide edition {meta.get('lastEdition')}) | verified: {a.verified} | generated by scripts/build_examples_catalogue.py -->",
        "",
        "# REST API examples catalogue",
        "",
        f"One row per example topic in the guide's **REST API Examples** chapter ({n} topics in {len(groups)} groups), with the",
        "request lines the topic shows (method, path, query string) and the features it says must be enabled. The row tells you",
        "which entity, action and `$expand`/`$select` shape Acumatica documents for a task; open the linked page for the request",
        "body, which is not reproduced here. Request lines are whitespace-collapsed; `<Acumatica ERP host>` is omitted.",
        "",
        "Endpoints seen: `Default` (the system endpoint) and `MANUFACTURING` (manufacturing entities); both at version",
        f"`26.200.001` in the {version} guide. Replace the version with the one your instance exposes (`GET /entity`).",
        "",
        "Grep by entity (`^## SalesOrder`), by action (`/ConfirmShipment`), by title words or by `$expand=` names.",
        "",
    ]
    for g in order:
        lines.append(f"## {g}")
        lines.append("")
        lines.append("| Example | Request(s) | Features required | Page |")
        lines.append("|---|---|---|---|")
        for e in groups[g]:
            req = "<br>".join(f"`{r}`" for r in e["requests"]) or "(no request line in the topic)"
            feats = "; ".join(e["features"]) or ""
            lines.append(f"| {e['title']} | {req} | {feats} | [page]({e['url']}) |")
        lines.append("")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{n} examples in {len(groups)} groups -> {a.out}")


if __name__ == "__main__":
    main()
